name: shift_handover_challenge
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  auto_route: any
  very_good_analysis: ^2.4.0
  dartz: ^0.10.1
  get_it: ^7.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  test: any
  mockito: ^5.0.17
  json_serializable: ^6.7.1
  auto_route_generator: any
  bloc_test: ^9.1.5

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
